### ISSUE TITLE
Error: App/Brackets/Brackets.exe

### ISSUE THREAD

**Issue by mrnate72** [sagiegurari/brackets-portable#18]
Hello, i installed this and extracted it and cannot find out what is wrong with it. It wont let me run the program. Here is the full error message:

Brackets Portable cannot be started. You may wish to re-install to fix this issue. (ERROR: App\Brackets\Brackets.exe could not be found)

Please help

**Comment by sagiegurari** [comment]
is it possible some anti virus deleted the exe? I did see some other av (see other older issues) that deleted the BracketPortable.exe (not that exe you had an error with) because it is not widely used or something.
So maybe some av decided to delete the Brackets.exe (which is really strange as it is the official adobe brackets exe).
But its a hunch.

**Comment by mrnate72** [comment]
I just got it working, thank you for your help. I did not install it through the exe file I just tried downloading the zip file
