### ISSUE TITLE
why can't I run brackets from program files folder?

### ISSUE THREAD

**Issue by ghost** [sagiegurari/brackets-portable#8]
Other portable apps I have can run from this folder, why don't brackets?

**Comment by sagiegurari** [comment]
I am not aware of any such limitation 
Any more info? Error? Something?

**Comment by ghost** [comment]
here is what I get when double clicking bracketsportable.exe
![1](https://cloud.githubusercontent.com/assets/17168621/13088547/59fdd42c-d4f5-11e5-8d8b-a240573d606b.png)

**Comment by sagiegurari** [comment]
ok, sorry but i'm using portableapps launcher and it doesn't support program files directory as it is for installable software.
in other words, put it anywhere else.
Personally i put all my portable software in a directory in the desktop, that way it is configured for my user only. For other users using that PC, i also put portable software under their user so they don't conflict and we don't mess each other configuration and so on...
unlike installed software which is only in 1 place, but configuration is split to the user directory, portable software keeps both software and config in same place and if it is not under a user directory it will be shared (config as well) between users, which is not recommanded, so this is basically by design of the portable launcher.

**Comment by ghost** [comment]
BTW, I'm using Firefox portable and I can run it from program files folder and it updates itself when a new Firefox comes out, meaning you don't need to make your own build for that. Just saying.

**Comment by sagiegurari** [comment]
not sure what firefox portable you are using as there are many, but i'm using portableapps.com launcher which generates that error popup you are seeing and by the way they also have firefox portable version using their launcher.

**Comment by ghost** [comment]
I'm using portableApps.com's Firefox and it works from program files and when ther's a new Firefox version I get the update popup. Maybe they changed something in their launcher?

Regarding the update, this is more for you, so you won't need to make a new package every time a new brackets is released.

**Comment by sagiegurari** [comment]
actually, the update of portableapps.com is part of the paf menu and not part of the launcher.
it checks for updates from paf sourceforge and downloads from there.
what you did, is i think, enabled the auto update of FF which means you are bypassing paf auto updates and could be an issue.
as for brackets, I don't limit any auto update feature it has if it has one, but since it is not 'installed' it might an issue for brackets to update itself.
I know it is not great, but that's best i can do right now.
