### ISSUE TITLE
Sometimes brackets lose its extensions

### ISSUE THREAD

**Issue by ghost** [sagiegurari/brackets-portable#9]
I know the extensions are installed here
C:\@Downloads\BracketsPortable\Data\home\AppData\Roaming\Brackets\extensions\user
but even thought I have the folders there, when I open brackets, all the extensions are gone. Before it happened when the extension got stuck and I needed to shut it down forcibly and this time it happened **after I opened brackets from a different folder (because of the other issue I opened here)**. Also when that happens, brackets open up with its default welcome project and not with the last folder I was in.

I made a test and installed an extension I already have and then searched for it. I found it in 2 places:
C:\Users\user\AppData\Roaming\Brackets\extensions\user - not good
C:\@Downloads\BracketsPortable\Data\home\AppData\Roaming\Brackets\extensions\user - good

Now it's stuck on the "not good" folder so even after closing and opening, it installs the extensions elsewhere and it's kinda losing the portable idea. It looks like it loses its pointers. Any idea what is causing this?

Addition: I copied the portable folder again to c:\program files, double clicked it, got the popup from my other issue and closed it. Then I double clicked the exe from the other location (c:\@downloads) and boom, all my extensions are back from the "good" folder. After some time, the extensions window got stuck so I had to kill it. Reopening it again made it loses the pointer and again it points to the remote location. Something is really wrong here.

**Comment by sagiegurari** [comment]
ok, sorry but i'm using portableapps launcher and it doesn't support program files directory as it is for installable software.
in other words, put it anywhere else.
Personally i put all my portable software in a directory in the desktop, that way it is configured for my user only. For other users using that PC, i also put portable software under their user so they don't conflict and we don't mess each other configuration and so on...
unlike installed software which is only in 1 place, but configuration is split to the user directory, portable software keeps both software and config in same place and if it is not under a user directory it will be shared (config as well) between users, which is not recommanded, so this is basically by design of the portable launcher.

**Comment by sagiegurari** [comment]
what version are you using?
really old versions used to copy from portable folder to appdata but new versions use BracketsPortable\Data\home\AppData\Roaming instead.

also program files is not supported, so drop that.

**Comment by ghost** [comment]
Your latest 1.6.0

It's not copying anything, the extensions in the portable folder C:\@Downloads\BracketsPortable\Data\home\AppData\Roaming\Brackets\extensions\user are still there but the application is looking in the non-portable folder: C:\Users\user\AppData\Roaming\Brackets\extensions\user

I didn't find any place to define this and it seems to be jumping from here to there and back with no apparent reason. Also notice that when it does the jump to the non-portable folder, it opens up as if it is opened for the very first time, even the brackets health report popup is showing up.

**Comment by sagiegurari** [comment]
what exe you are running?

**Comment by ghost** [comment]
Yeah, silly me I guess. After opening brackets, I pinned it to the taskbar but apparently I pinned the .exe itself and not the wrapper exe that makes it portable. You can close this issue.
